FROM node:20-alpine

WORKDIR /app

COPY frontend/package*.json /app/frontend/
RUN cd /app/frontend && npm install

COPY frontend /app/frontend

WORKDIR /app/frontend

EXPOSE 3000

CMD ["npm", "start", "--", "--host", "0.0.0.0"]
